### ISSUE TITLE
CU Lyrics

### ISSUE THREAD

**Issue by jarrodprice** [rivy/xbmc-script.audio.pandora#12]
I was wondering if there was a way to get the lyrics plugin to work with Pandora?

**Comment by Kuki77** [comment]
The lyrics plugin works only accidentally. 

Please fix:
- Lyrics function
- Lyrics should not be in focus, when starting playing a new song (pressing Esc/back/exit alway needed).

Please add as function:
- Disabling lyrics completely in the settings.

EDIT:

Sorry, but the problem with the lyrics is appearing only with the Amber skin, not in Confluence skin.
So: not a pandora issue!

**Comment by rivy** [comment]
Seems to be skin specific lyrics issues... no bug here.
