### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by iondiode** [rivy/xbmc-script.audio.pandora#18]
(I may have entered this already on the wrong repo) 

Recently Pandora Json just stopped authenticating. Web works, Phone works, no changes that I'm aware of.

Does anyone else see this?

**Comment by cliffsch** [comment]
Mine’s working fine.

Pandora One subscriber
Pandora add-on 2.3.2
XBMC 12.3 on Windows 7

**Comment by iondiode** [comment]
Hrm, I am not a pandora one subscriber, but it looks like my version is very old (1.3.02) , I'll try updating
