### ISSUE TITLE
Visualizer Set to "None" crashes(?) Pandora instance

### ISSUE THREAD

**Issue by logannc** [rivy/xbmc-script.audio.pandora#2]
If the visualizer is set to "None" and you select a station, it will close when it starts playing. It will finish out the song but the Pandora instance in closed so you cannot re-open the Pandora add-on and control it from there. (Well, you can pause it but Skip and "I'm Tired" buttons don't seem to work and I've not noticed any functionality whatsoever for the Thumb buttons).

I have to open up the "Now Playing" thing and then skip the song and it beeps telling me it can't find the next song, further indicating the Pandora instance is closed.

Feature request: I'm unfamiliar with the environment of XBMC plugins, add-ons etc, but if the plugin could "re-attach" to the previous or current background Pandora instance, I think it would solve the issue(s) I am describing.

**Comment by rivy** [comment]
I've not seen this... I'll see if I can reproduce this on my XBMC.

**Comment by rivy** [comment]
I'm unable to reproduce this issue. Would you get the most recent update and see if you're still having the issue?
