### ISSUE TITLE
Skipping Song crashes(?) Pandora instance

### ISSUE THREAD

**Issue by logannc** [rivy/xbmc-script.audio.pandora#3]
Skipping the song results in the song being skipped, but being put back at the music add-on selection. Same as before, I can re-open the pandora script but I cannot control it again (ie, skip this song) without going to the now playing thing.

**Comment by rivy** [comment]
There were some issues with changes in Pandora protocols last year. I think it's all been ironed out.

Please pull the latest master and see if the issue is fixed for you. If not, re-open this issue, and I'll try to look into it further.
