### ISSUE TITLE
Dependencies not met - What dependencies? 

### ISSUE THREAD

**Issue by davewithhemp** [rivy/xbmc-script.audio.pandora#4]
I'm not able to install from zip. Dependencies not met. Python 3.3.3. XBMC 13.0 Alpha 11. Is this Beta the problem?

**Comment by rivy** [comment]
Can you give me some more insight into the error? 

What OS are you using? Can you supply a  debug log?

The current revision installs easily without issue on a fresh Frodo 12.3 / Windows build. Beyond that, I'm in unknown waters at this point, and will need some help to navigate around the shoals.

Thanks.

**Comment by davewithhemp** [comment]
Sorry for the delayed reply. I'm using Win7x64. I really shouldn't
have posed this issue without "downgrading" to an official release...
which I'll probably do. Just out of curriousity though, XBMC is having
a feature freeze. Does this mean they are getting ready to do an
official release of v13? Anyways, Thanks for this add-on. I couldn't
live without it. Keep up the good work. It's much appreciated.

**Comment by rivy** [comment]
My bet is that betas for v13/Gotham will be released in the next few weeks, although I've not seen anything definitive from the XBMC team on a timeline. In preparation, I'm doing some work now to retool the plugin to correspond better with Frodo & Gotham recommendations for API and code structure.

In the current code, the only "dependency" that seems reasonable is xbmc.python, v1.0, listed in addon.xml. Frodo recommendations include a change to xbmc.python v2.1.0, though the plugin functions fine, in Frodo, with v1.0 specified. I wonder whether v1.0 has been removed from Gotham. Maybe that's the reason for the "missing dependency" error. A debug log of the error might shed more light on it.

But anyway, while attempting to refactor this, I'm trying to hit all the official Frodo recommendations (including changing to xbmc.python v2.1.0). Subsequently, when a beta comes out (or I get a chance to play with the alpha), I'll add a Gotham version.

Let me know if you get any more information about the "missing dependency". Thanks.

**Comment by rivy** [comment]
@davewithhemp,

Try the "test-gotham" branch; my most recent commit to it is f635e2dd4d7ea9a0ef4bc40005f53653dd42ae2a.

Included with various other changes & an ongoing update, I upgraded the xbmc.python required version to "v2.1.0". With that change, it's working for me in both Frodo and Gotham (alpha 11, monthly build).

Let me know if it works for you, as well.

**Comment by davewithhemp** [comment]
Will do! Thanks!
